In [2]:

import tensorflow as tf
import os
import numpy as np
import random
import cv2 as cv



import matplotlib.pyplot as plt

##from skimage.io import imread,imshow

model = tf.keras.models.load_model('Modelv1',compile=False)

data = np.load('data.npz')
X_train = data['X_train']
X_test = data['X_test']
Y_test = data['Y_test']

preds_test = model.predict(X_test)
#preds_test = (preds_test > 0.5).astype(np.uint8)












2023-04-09 19:56:33.447781: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-09 19:56:39.667406: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-09 19:56:39.669364: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


4/4 [==============================] - 4s 707ms/step


In [3]:
preds_test = (preds_test > 0.5).astype(np.uint8)
1 in preds_test[0]

True

In [4]:
ix = random.randint(0, len(X_test))
img = cv.cvtColor(X_test[1],cv.COLOR_BGR2GRAY)
img2=np.array(preds_test[1]).astype('uint8')

# img2 = img2.transpose(2,0,1).reshape(128,-1)


for i in range(img2.shape[0]):
    for j in range(img2.shape[1]):
        if img2[i][j] == 1:
            img2[i][j] = 255


cv.imshow('X',img)
cv.waitKey(0)
# cv.imshow('Y',np.array(Y_test[ix]).astype('uint8'))
cv.imshow('Pred',img2)





cv.waitKey(0)
cv.destroyAllWindows()



In [5]:
contours, hierarchy = cv.findContours(img2,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE)

In [40]:
c = contours
c = list(c[5])
c_sort_by_y = sorted(c,key = lambda x : x[0][1])
c_sort_by_x = sorted(c,key = lambda x : x[0][0])
c_sort_by_y

[array([[67,  0]], dtype=int32),
 array([[72,  0]], dtype=int32),
 array([[72,  1]], dtype=int32),
 array([[67,  2]], dtype=int32),
 array([[76,  2]], dtype=int32),
 array([[73,  2]], dtype=int32),
 array([[66,  3]], dtype=int32),
 array([[64,  3]], dtype=int32),
 array([[66,  3]], dtype=int32),
 array([[67,  4]], dtype=int32),
 array([[67,  6]], dtype=int32),
 array([[66,  7]], dtype=int32),
 array([[65,  7]], dtype=int32),
 array([[66,  7]], dtype=int32),
 array([[67,  8]], dtype=int32),
 array([[67, 10]], dtype=int32),
 array([[66, 11]], dtype=int32),
 array([[64, 11]], dtype=int32),
 array([[65, 12]], dtype=int32),
 array([[66, 12]], dtype=int32),
 array([[64, 13]], dtype=int32),
 array([[67, 13]], dtype=int32),
 array([[67, 14]], dtype=int32),
 array([[66, 15]], dtype=int32),
 array([[63, 15]], dtype=int32),
 array([[64, 16]], dtype=int32),
 array([[73, 16]], dtype=int32),
 array([[74, 16]], dtype=int32),
 array([[76, 16]], dtype=int32),
 array([[63, 17]], dtype=int32),
 array([[6

In [47]:


def getBaseWidthAndHeight(arr:list):
    min_y = arr[len(arr)-1][0][1]
    max_y = arr[0][0][1]
    range = (min_y - max_y)/10
    min_x = arr[len(arr)-1][0][0]
    max_x = arr[len(arr)-1][0][0]
    #print('hehe',max_x,min_x,range,max_y,min_y,min_y-range)

    
    i = len(arr)-1
    while i >= 0:
        if(arr[i][0][1] < int(min_y-range)):
            break
        if(arr[i][0][0] > max_x):
            max_x = arr[i][0][0]
        if(arr[i][0][0] < min_x):
            min_x = arr[i][0][0]
        i = i -1

    return max_x - min_x,min_y-max_y

# getBaseWidth_Height(c_sort_by_y)

def getSymmetryScore(arr:list):
    min_y = arr[len(arr)-1][0][1]
    max_y = arr[0][0][1]






6

In [ ]:
a = np.array([[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]])
np.sort(a, axis= 1, kind=None, order=None) 

array([[10, 11, 13, 22],
       [ 7, 14, 20, 23],
       [11, 17, 31, 33]])